// <auto-generated />
using System;
using EggBasket.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EggBasket.Migrations
{
    [DbContext(typeof(CredentialContext))]
    [Migration("20211120234314_test")]
    partial class test
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EggBasket.Models.Credential", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("company")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("personal")
                        .HasColumnType("bit");

                    b.Property<string>("roleID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("secureNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Credential");
                });

            modelBuilder.Entity("EggBasket.Models.Wrapper", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CredentialID")
                        .HasColumnType("int");

                    b.Property<string>("userid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CredentialID");

                    b.ToTable("Wrapper");
                });

            modelBuilder.Entity("EggBasket.Models.Wrapper", b =>
                {
                    b.HasOne("EggBasket.Models.Credential", null)
                        .WithMany("userIds")
                        .HasForeignKey("CredentialID");
                });

            modelBuilder.Entity("EggBasket.Models.Credential", b =>
                {
                    b.Navigation("userIds");
                });
#pragma warning restore 612, 618
        }
    }
}
